# **Hybrid Collaborative Filtering Book Recommender based on Popularity, KNN, SVD**

## **Load saved pkls & csvs**

In [3]:
import joblib
import pandas as pd

dir_knn = "knn_pkls"
dir_svd = "svd_pkls"
dir_pop = "popularity_csv"



# Load SVD
svd_model = joblib.load(f"{dir_svd}/svd_model.pkl")
train_ratings_svd = pd.read_csv(f"{dir_svd}/train_ratings_svd.csv")
test_ratings = pd.read_csv(f"{dir_svd}/test_ratings_svd.csv")

# Load KNN
knn_model = joblib.load(f"{dir_knn}/knn_model.pkl")
train_ratings_knn = pd.read_csv(f"{dir_knn}/train_ratings_knn.csv")
book_pivot_knn = joblib.load(f"{dir_knn}/book_pivot_knn.joblib")

# Load popularity
popularity_df = pd.read_csv(f"{dir_pop}/popularity_df.csv")

In [4]:
train_ratings_svd.head(3)

,user_id,isbn,ratings,title,author,year,publisher,img_url
0,254,0451150244,0,Pet Sematary,Stephen King,1984,Signet Book,http://images.amazon.com/images/P/0451150244.0...
1,254,0441003257,0,Good Omens,Neil Gaiman,1996,Ace Books,http://images.amazon.com/images/P/0441003257.0...
2,254,0316569321,0,White Oleander : A Novel,Janet Fitch,1999,"Little, Brown",http://images.amazon.com/images/P/0316569321.0...

In [5]:
test_ratings.head(3)

,user_id,isbn,ratings,title,author,year,publisher,img_url
0,254,0060930535,0,The Poisonwood Bible: A Novel,Barbara Kingsolver,1999,Perennial,http://images.amazon.com/images/P/0060930535.0...
1,254,0141301066,0,Matilda,Roald Dahl,1998,Puffin Books,http://images.amazon.com/images/P/0141301066.0...
2,254,0446605239,0,The Notebook,Nicholas Sparks,1998,Warner Books,http://images.amazon.com/images/P/0446605239.0...

In [6]:
train_ratings_knn.head(3)

,user_id,isbn,ratings,title,author,year,publisher,img_url
0,254,0439136350,9,Harry Potter and the Prisoner of Azkaban (Book 3),J. K. Rowling,1999,Scholastic,http://images.amazon.com/images/P/0439136350.0...
1,254,014028009X,0,Bridget Jones's Diary,Helen Fielding,1999,Penguin Books,http://images.amazon.com/images/P/014028009X.0...
2,254,067976402X,0,Snow Falling on Cedars,David Guterson,1995,Vintage Books USA,http://images.amazon.com/images/P/067976402X.0...

In [7]:
popularity_df.head(3)

,title,rating_count,avg_rating,score
0,The Lovely Bones: A Novel,225,3.355556,755.0
1,Harry Potter and the Chamber of Secrets (Book 2),141,3.978723,561.0
2,The Da Vinci Code,182,2.901099,528.0

In [8]:
book_pivot_knn

user_id,254,2276,2766,2977,3363,4017,6242,6251,6323,6543,...,274004,274061,274301,274308,274808,275970,277427,277478,277639,278418
title,,,,,,,,,,,,,,,,,,,,,
1st to Die: A Novel,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2nd Chance,0.0,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
A Bend in the Road,0.0,0.0,7.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
A Is for Alibi (Kinsey Millhone Mysteries (Paperback)),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
A Map of the World,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
White Oleander : A Novel,0.0,0.0,0.0,7.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
White Oleander : A Novel (Oprah's Book Club),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Wicked: The Life and Times of the Wicked Witch of the West,0.0,0.0,0.0,0.0,0.0,0.0,7.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Wild Animus,0.0,0.0,6.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"\O\"" Is for Outlaw""",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,8.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

## **normalize popularity scores**

In [9]:
def normalizer_for_pop(popularity_df):

    # Crate new column for popularity score based on weights
    if "pop_score" not in popularity_df.columns:
        # Weighted combination of avg_rating and rating_count
        popularity_df["pop_score"] = (
            popularity_df["avg_rating"] * 0.7 + popularity_df["rating_count"] * 0.3
        )
    # Normalize to 0-1
    popularity_df["pop_score"] /= popularity_df["pop_score"].max()

    return popularity_df

In [10]:
normalizer_for_pop(popularity_df)
popularity_df.head()

,title,rating_count,avg_rating,score,pop_score
0,The Lovely Bones: A Novel,225,3.355556,755.0,0.760838
1,Harry Potter and the Chamber of Secrets (Book 2),141,3.978723,561.0,0.491095
2,The Da Vinci Code,182,2.901099,528.0,0.616858
3,To Kill a Mockingbird,138,3.644928,503.0,0.478747
4,Harry Potter and the Prisoner of Azkaban (Book 3),109,4.394495,479.0,0.389696

## **predict SVD scores for a user**

In [11]:
# Get the svd predicted scores(ratings) for unseen books i.e) boooks that user hasn't rated for a particular user

"""
scores finally should look :

"title" : normalized ratings of model predicted ratings

scores = {
 'Cradle and All': 0.0,             # Score = 0 means : Model thinks the user probably won’t like these
 'Disclosure': 0.19939775974208668,
 'Southern Cross': 0.3618182812111125,
 'Watership Down': 0.0,
 'When the Wind Blows': 0.0,
 "The Handmaid's Tale": 0.48606019878318346,
 'Skipping Christmas': 0.8556410644843749,...
 }
"""

def svd_scores_for_user(user_id, train_ratings_svd):
    all_books = train_ratings_svd["title"].unique()
    rated_books = train_ratings_svd[train_ratings_svd["user_id"]==user_id]["title"]
    unseen_books = [b for b in all_books if b not in rated_books.values]
    
    scores = {}
    for book in unseen_books:
        scores[book] = svd_model.predict(user_id, book).est
    
    # Normalize
    if scores:
        max_score = max(scores.values())
        for book in scores:
            scores[book] /= max_score
            
    # return list of books that can be suggest to a particular user with model predeicted score that measure how far each book related
    return scores # dictionary of (title : normalized_score of predicted ratings)

In [26]:
dic_svd_score = svd_scores_for_user(254, train_ratings_svd) # based on user
dic_svd_score # all score values for books for user 254 / how much each book match with user 0 - not, 1 - best

{'Midnight in the Garden of Good and Evil: A Savannah Story': 0.42347541265781424,
 'The Bourne Ultimatum': 0.22302058594815127,
 'The King of Torts': 0.2888509563085016,
 'The Eight': 0.285132655344653,
 'Skipping Christmas': 0.678461317691598,
 '2nd Chance': 0.43235905557280147,
 'Contagion': 0.1933505691835462,
 'Roses Are Red (Alex Cross Novels)': 0.39330010907768953,
 'The Brethren': 0.41289711225241904,
 'The Valley of Horses': 0.5167359960331201,
 'The Tale of the Body Thief (Vampire Chronicles (Paperback))': 0.43666123380205707,
 'Disclosure': 0.2993349528778847,
 'Dust to Dust': 0.22828950014272842,
 'Watership Down': 0.5407455932634624,
 'Insomnia': 0.509720380759488,
 'Touching Evil': 0.3478383835141912,
 'Misery': 0.44960200504707715,
 'Nickel and Dimed: On (Not) Getting By in America': 0.6780920168416762,
 'The Dark Half': 0.34960052155893445,
 'Southern Cross': 0.4187350925324053,
 'The Runaway Jury': 0.5449202292500617,
 'When the Wind Blows': 0.4498788282886045,
 'Cause of Death': 0.2899475995166343,
 "White Oleander : A Novel (Oprah's Book Club)": 0.2498959390582442,
 'The Long Road Home': 0.25350500240435886,
 'Over the Edge': 0.3580551700109594,
 'Strangers': 0.2111683435201856,
 "It's Always Something": 0.4036392735816453,
 'Wild Animus': 0.04641927290101855,
 'Congo': 0.3062741542152181,
 'Big Trouble': 0.5037365516833875,
 'Snow Falling on Cedars': 0.37047071617341265,
 'Seabiscuit: An American Legend': 0.48582453200010256,
 'To Kill a Mockingbird': 0.857253188987207,
 'Stupid White Men ...and Other Sorry Excuses for the State of the Nation!': 0.7291713602565305,
 'Message in a Bottle': 0.379411313003173,
 "The Hitchhiker's Guide to the Galaxy": 0.5946282227780287,
 'A Case of Need': 0.2742007406440636,
 'Five Quarters of the Orange': 0.4918927321934441,
 'At Home in Mitford (The Mitford Years)': 0.39132817620005794,
 'The Pelican Brief': 0.46686374071461906,
 'Matilda': 0.6003781990463194,
 'A Is for Alibi (Kinsey Millhone Mysteries (Paperback))': 0.5488627933879634,
 'The Glass Lake': 0.3602014065233484,
 'The Color Purple': 0.611225951271534,
 'Intensity': 0.4571516526668504,
 'The Giver (21st Century Reference)': 0.5128389076768046,
 'Daddy': 0.32348072127467903,
 "The Color of Water: A Black Man's Tribute to His White Mother": 0.5648166938244411,
 'The Copper Beech': 0.21643534866965303,
 'The Lovely Bones: A Novel': 0.7435800985180705,
 'Angels': 0.3946335947061301,
 'Into the Wild': 0.4197736250014862,
 'Slow Waltz in Cedar Bend': 0.36159086759148484,
 'Jurassic Park': 0.6429623988229932,
 'K Is for Killer (Kinsey Millhone Mysteries (Paperback))': 0.4586737543470683,
 'The Firm': 0.4023908343872618,
 'Drowning Ruth': 0.23521700059912434,
 'Balzac and the Little Chinese Seamstress : A Novel': 0.43465173949326436,
 'The Testament': 0.40169645819806665,
 'The Robber Bride': 0.2985620594451814,
 'A Heartbreaking Work of Staggering Genius': 0.4530818445804392,
 'Winter Moon': 0.1596253412573681,
 "Where the Heart Is (Oprah's Book Club (Paperback))": 0.5976579044894825,
 'Mortal Fear': 0.36939589603362694,
 'Angus, Thongs and Full-Frontal Snogging: Confessions of Georgia Nicolson': 0.5483082118914888,
 'Hannibal': 0.4066647783836529,
 'Like Water for Chocolate: A Novel in Monthly Installments, With Recipes, Romances, and Home Remedies': 0.3877945001426699,
 "She's Come Undone (Oprah's Book Club (Paperback))": 0.5967210762972599,
 'Invasion': 0.20839552511511067,
 'The Alibi': 0.33946817960959896,
 'The Talisman': 0.38072388435707905,
 'Zen and the Art of Motorcycle Maintenance: An Inquiry into Values': 0.1983959876525475,
 'Beach House': 0.2391569778331995,
 'Wicked: The Life and Times of the Wicked Witch of the West': 0.43745033483949486,
 "Chicken Soup for the Woman's Soul (Chicken Soup for the Soul Series (Paper))": 0.503144891276199,
 'Interview with the Vampire': 0.7468381085402922,
 'While My Pretty One Sleeps': 0.2763955695428589,
 "Big Cherry Holler: A Big Stone Gap Novel (Ballantine Reader's Circle)": 0.6399512676477478,
 'Point of Origin': 0.48316512080621016,
 "The Girls' Guide to Hunting and Fishing": 0.30056857746349097,
 'The Divine Secrets of the Ya-Ya Sisterhood: A Novel': 0.46203417501070193,
 'The Da Vinci Code': 0.8082660669774377,
 'Confessions of an Ugly Stepsister : A Novel': 0.3199940334712792,
 'Little Altars Everywhere: A Novel': 0.47581913145223365,
 'The Client': 0.42986477537775075,
 'Welcome to the World, Baby Girl!': 0.2809399268133391,
 'Temptation': 0.258167726668578,
 'Daisy Fay and the Miracle Man': 0.414093037579522,
 'Red Dragon': 0.3705723261880933,
 'Chicken Soup for the Soul (Chicken Soup for the Soul)': 0.43517457319408825,
 'Lucky : A Memoir': 0.4729212590952776,
 'Plainsong (Vintage Contemporaries)': 0.448604548618245,
 "Tom Clancy's Op-Center (Tom Clancy's Op Center (Paperback))": 0.3334349436114782,
 'Breath, Eyes, Memory': 0.39319387552772433,
 'Timeline': 0.4414089073615852,
 'All I Really Need to Know': 0.43570089066956363,
 'The Honk and Holler Opening Soon': 0.38676958182546306,
 'The Tao of Pooh': 0.4458946805768053,
 'Confessions of a Shopaholic (Summer Display Opportunity)': 0.550311453680202,
 "What to Expect When You're Expecting (Revised Edition)": 0.3696276803382118,
 'Dance upon the Air (Three Sisters Island Trilogy)': 0.2568420500278645,
 'Body of Lies': 0.3310339877431971,
 'Jemima J: A Novel About Ugly Ducklings and Swans': 0.28687825468172634,
 'The Chamber': 0.41889715501602914,
 'Empire Falls': 0.42802535588632445,
 'The Boy Next Door': 0.5185294095029168,
 'Saving Faith': 0.23003803210659782,
 'Rising Sun': 0.32647904293459623,
 'The Poisonwood Bible': 0.3611475623128825,
 'Sleepers': 0.3093180215174874,
 'Nicolae: The Rise of Antichrist (Left Behind No. 3)': 0.4855011496036404,
 "The Princess Bride: S Morgenstern's Classic Tale of True Love and High Adventure": 0.5944056032095354,
 "Don't Sweat the Small Stuff and It's All Small Stuff : Simple Ways to Keep the Little Things from Taking Over Your Life (Don't Sweat the Small Stuff Series)": 0.43733978703293536,
 'The Nanny Diaries: A Novel': 0.36506003948217636,
 'The Notebook': 0.4776250491075373,
 "Songs in Ordinary Time (Oprah's Book Club (Paperback))": 0.18966872382906716,
 'Life of Pi': 0.518700718354841,
 'The Bonfire of the Vanities': 0.37937719999441494,
 'A Widow for One Year': 0.20934803825659712,
 'Peace Like a River': 0.6286641439852332,
 'The Bluest Eye': 0.37605074901911967,
 'Blessings': 0.288719326926786,
 "Song of Solomon (Oprah's Book Club (Paperback))": 0.25893604310776974,
 'Falling Angels': 0.26270350266034775,
 'The Bean Trees': 0.6767055478164256,
 'We Were the Mulvaneys': 0.24174509683147014,
 'Beloved': 0.5429331650949976,
 "Harry Potter and the Sorcerer's Stone (Harry Potter (Paperback))": 0.7081536636593103,
 'Divine Secrets of the Ya-Ya Sisterhood: A Novel': 0.3589963060301084,
 "The Book of Ruth (Oprah's Book Club (Paperback))": 0.33291527238285873,
 'Brave New World': 0.4949309064619714,
 'Jewel': 0.3631543128445736,
 'Bridget Jones : The Edge of Reason': 0.38121349545167343,
 'STONES FROM THE RIVER': 0.281372032800089,
 'One True Thing': 0.2966573684305703,
 "Vinegar Hill (Oprah's Book Club (Paperback))": 0.40860338882392444,
 'Mother of Pearl': 0.2590175161949767,
 'While I Was Gone': 0.3483157484444682,
 'Range of Motion': 0.4303082307227654,
 'Bel Canto: A Novel': 0.615418669135324,
 'I Know This Much Is True': 0.5411408603261825,
 'Into Thin Air : A Personal Account of the Mt. Everest Disaster': 0.457065982953967,
 'The Reader': 0.14549719512744108,
 'The Cider House Rules': 0.2104995615694406,
 'Cold Mountain': 0.2811310100662569,
 'Midnight in the Garden of Good and Evil': 0.6304576172667791,
 'Beloved (Plume Contemporary Fiction)': 0.3870258263780555,
 'How to Be Good': 0.21915204972033073,
 'Girl, Interrupted': 0.5469658580710871,
 'Year of Wonders': 0.5011926564611657,
 'About a Boy': 0.3976450153682159,
 'Vanished': 0.23531682601506868,
 'A Painted House': 0.42088439186996235,
 'Dying for Chocolate (Culinary Mysteries (Paperback))': 0.3916056288436295,
 'Fatherhood': 0.35968512193025487,
 'River, Cross My Heart': 0.2917292153343864,
 'Isle of Dogs': 0.34237722363540074,
 'Lucky Man: A Memoir': 0.564637468616739,
 'The Hundred Secret Senses': 0.3642467926500762,
 'The Crimson Petal and the White': 0.4499443235062803,
 "The Handmaid's Tale": 0.7106355675917272,
 'The Five People You Meet in Heaven': 0.7893549526716072,
 'The Partner': 0.5120082877701903,
 "The No. 1 Ladies' Detective Agency (Today Show Book Club #8)": 0.57266553472262,
 'The Diary of Ellen Rimbauer: My Life at Rose Red': 0.2743268305126151,
 'The Bad Beginning (A Series of Unfortunate Events, Book 1)': 0.5022631050225671,
 'The Angel of Darkness': 0.21299514884040774,
 'The Smoke Jumper': 0.29403425434063674,
 'Sick Puppy': 0.401261364898005,
 'How to Make an American Quilt': 0.2799099672203862,
 'Prime Cut': 0.3293637575474027,
 'Dragon Tears': 0.28286213594599846,
 "Dude, Where's My Country?": 0.7133390015233534,
 'Cruel &amp; Unusual (Kay Scarpetta Mysteries (Paperback))': 0.48921753146739605,
 "Tuesdays with Morrie: An Old Man, a Young Man, and Life's Greatest Lesson": 0.6858385202420375,
 'A Man in Full': 0.4041760709155435,
 'Seabiscuit': 0.3207025911917347,
 'The Bourne Identity': 0.43712421132155965,
 'One for the Money (Stephanie Plum Novels (Paperback))': 0.48624746998565227,
 'Nerd in Shining Armor': 0.6121138711414618,
 'The God of Small Things': 0.34039832524042485,
 'Good in Bed': 0.5120911507458874,
 'The Perfect Storm : A True Story of Men Against the Sea': 0.3788486349485661,
 'The Alienist': 0.36062708208329897,
 'Fast Food Nation: The Dark Side of the All-American Meal': 0.6173208017836699,
 'Body of Evidence (Kay Scarpetta Mysteries (Paperback))': 0.43544419848399324,
 'A Wrinkle In Time': 0.5182622337146069,
 'FORREST GUMP (Movie Tie in)': 0.3858192067076082,
 'The English Patient': 0.40066234744516516,
 'Without Remorse': 0.40694776936349913,
 'The Wedding': 0.4589015891285148,
 'Couplehood': 0.3282691257419368,
 'Morality for Beautiful Girls (No.1 Ladies Detective Agency)': 0.46305180527059975,
 'The Rescue': 0.5292065401003122,
 'Tears of the Giraffe (No.1 Ladies Detective Agency)': 0.6620285887490436,
 'Mystic River': 0.40233990274533443,
 'Night': 0.42806645796298265,
 'The Hot Zone': 0.5600103786227317,
 '4 Blondes': 0.30583658578685097,
 'Artemis Fowl (Artemis Fowl, Book 1)': 0.4810361373177166,
 "The General's Daughter": 0.3119125282392598,
 "Ender's Game (Ender Wiggins Saga (Paperback))": 0.6911818550715177,
 "Smilla's Sense of Snow": 0.24227824428625852,
 "Angela's Ashes: A Memoir": 0.5552639519998532,
 'The Kiss': 0.3512193863427941,
 'Fried Green Tomatoes at the Whistle Stop Cafe': 0.3560110085905591,
 'The Devil Wears Prada : A Novel': 0.35849084343351983,
 "Full House (Janet Evanovich's Full Series)": 0.5943922320801878,
 'The Poisonwood Bible: A Novel': 0.41572913844461895,
 "Jewel (Oprah's Book Club)": 0.33938046536825744,
 'The Most Wanted': 0.16178891505425202,
 'L Is for Lawless': 0.4144762400172791,
 'It Was on Fire When I Lay Down on It': 0.40519665513974334,
 'Seven Up (A Stephanie Plum Novel)': 0.6487721496604679,
 'Holes (Yearling Newbery)': 0.5870609782818206,
 'Primary Colors: A Novel of Politics': 0.2512557782665685,
 'Slammerkin': 0.2951401764704008,
 "CAT'S EYE": 0.28945551272019154,
 'The Queen of the Damned (Vampire Chronicles (Paperback))': 0.420458610364724,
 'Unnatural Exposure': 0.35721641730224235,
 'Acceptable Risk': 0.4616619538259704,
 'You Belong To Me': 0.2612882044105537,
 "Hornet's Nest": 0.4396764076855891,
 'All Around the Town': 0.5759413980898578,
 'Loves Music, Loves to Dance': 0.3446336146426595,
 'Pleading Guilty': 0.1807118883820962,
 'Postmortem': 0.5094179419794002,
 'Silent Witness': 0.2485032572266181,
 'Pop Goes the Weasel': 0.38953145608572054,
 'Ashes to Ashes': 0.32643824164250146,
 'Moonlight Becomes You': 0.5644324776145551,
 'Death du Jour': 0.4947162937953718,
 'The Last Precinct': 0.42640272727967676,
 'The Murder Book': 0.32846177496932033,
 'Q Is for Quarry': 0.617892562427654,
 '1st to Die: A Novel': 0.507892949881071,
 "Schindler's List": 0.4230076309220469,
 'Hot Six : A Stephanie Plum Novel (A Stephanie Plum Novel)': 0.3869088901951938,
 'Catering to Nobody': 0.44070185776106774,
 'The Surgeon': 0.40567024883067165,
 'The Other Boleyn Girl': 0.5048999601024874,
 'Three Junes': 0.41972972190163915,
 'Violets Are Blue': 0.44649164017783183,
 "Lamb : The Gospel According to Biff, Christ's Childhood Pal": 0.6074267713637223,
 'Miss Julia Speaks Her Mind : A Novel': 0.43898797264762807,
 'Naked': 0.5394244560449548,
 'Love in the Time of Cholera (Penguin Great Books of the 20th Century)': 0.3924679457912194,
 'Outlander': 0.5473307191497633,
 "Big Stone Gap: A Novel (Ballantine Reader's Circle)": 0.5060951753840012,
 'The Red Tent (Bestselling Backlist)': 0.7198419461074382,
 'Fahrenheit 451': 0.7329686586274475,
 'The Jester': 0.36013518200531247,
 'Two for the Dough': 0.5179997596241419,
 'High Five (A Stephanie Plum Novel)': 0.5360609495690056,
 "Suzanne's Diary for Nicholas": 0.4893507448645218,
 'A Walk to Remember': 0.39884314545624155,
 'Beach Music': 0.3745726899638646,
 'Scarlet Feather': 0.3316277537193667,
 'A Patchwork Planet': 0.30258254415554603,
 'The Saving Graces: A Novel': 0.3897552947330219,
 'Girl in Hyacinth Blue': 0.4965648288977701,
 'Cradle and All': 0.3446716467492297,
 'GARDEN OF SHADOWS (Dollanger Saga (Paperback))': 0.2942262242889222,
 'Family Album': 0.33467395160815416,
 'Jacob Have I Loved': 0.2321339353938996,
 'The Return Journey': 0.16008713178874756,
 'Crazy for You': 0.30499652806023425,
 'Flesh and Blood': 0.2865840898201991,
 'Echoes': 0.25203810583907565,
 'Four Blind Mice': 0.3819911079112792,
 'Shopaholic Takes Manhattan (Summer Display Opportunity)': 0.3774168217113448,
 "The Sweet Potato Queens' Book of Love": 0.39768612784857976,
 'Sanctuary': 0.2637249256794787,
 'What Looks Like Crazy On An Ordinary Day': 0.4714692749764781,
 'The Burden of Proof': 0.35226636776979486,
 'Pigs in Heaven': 0.34307500651688627,
 "Fortune's Rocks: A Novel": 0.5151129035444784,
 'Under the Tuscan Sun': 0.4664205716121782,
 'The Edge': 0.2810406526137799,
 'Summer Sisters': 0.39921854233712634,
 'SHIPPING NEWS': 0.3535105292962413,
 'The Last Time They Met : A Novel': 0.2633735512926615,
 'To the Nines: A Stephanie Plum Novel': 0.4852196663234582,
 'Fat Tuesday': 0.08224056919880224,
 'The Virgin Suicides': 0.5208414371916983,
 'One for the Money (A Stephanie Plum Novel)': 0.7286567949314525,
 'In Her Shoes : A Novel': 0.6168020775651805,
 'The Prince of Tides': 0.5191960049758779,
 'The Horse Whisperer': 0.3087407495484145,
 'Turtle Moon': 0.3996230018799185,
 'Notes from a Small Island': 0.44842980491474693,
 'The Beach House': 0.1363402754825678,
 'Three To Get Deadly : A Stephanie Plum Novel (A Stephanie Plum Novel)': 0.4142392504301262,
 "River's End": 0.27650998516631364,
 'Hard Eight : A Stephanie Plum Novel (A Stephanie Plum Novel)': 0.6254982057701569,
 'Blue Diary': 0.33207255651061696,
 'A Civil Action': 0.216136240148445,
 'Fast Women': 0.2594775063189661,
 'Waiting to Exhale': 0.2842826389376837,
 'Final Target': 0.2651455681801751,
 'A Fine Balance': 0.28351800798115045,
 'Secret History': 0.2835642101110671,
 "Full Tilt (Janet Evanovich's Full Series)": 0.3914399986648917,
 'A Map of the World': 0.2705076187311678,
 'The Celestine Prophecy (Celestine Prophecy)': 0.5027457031965077,
 'Carolina Moon': 0.32169787645909337,
 "The Pilot's Wife : A Novel": 0.5102699980801241,
 'Midwives: A Novel': 0.47795069592215594,
 'Bastard Out of Carolina': 0.5999697041368316,
 'Cold Mountain : A Novel': 0.29853035389295746,
 "The Idiot Girls' Action Adventure Club": 0.539796699091208,
 'White Teeth: A Novel': 0.22227888675529311,
 'All the Pretty Horses (The Border Trilogy, Vol 1)': 0.23338889430428075,
 "A Thousand Acres (Ballantine Reader's Circle)": 0.38524743996342176,
 'Kiss the Girls': 0.4925522656344094,
 'Fingersmith': 0.5966528859304745,
 'Atonement : A Novel': 0.24713706349049247,
 'How Stella Got Her Groove Back': 0.30600841389102923,
 'N Is for Noose': 0.4085629737052595,
 'False Memory': 0.404563697883251,
 'The Summerhouse': 0.312996423030414,
 'The Weight of Water : A Novel Tag: Author of Resistance and Strange Fits of Passion': 0.30658351594213623,
 'Black and Blue': 0.3067440235232673,
 'Nights in Rodanthe': 0.3501216142545509,
 'Bleachers': 0.47130086944075167,
 'Where the Red Fern Grows': 0.8459278116367325,
 'Dreamcatcher': 0.5233601771542865,
 'Watchers': 0.4658317809266686,
 'Small Town Girl': 0.4489895003691789,
 'The Dogs of Babel (Today Show Book Club #12)': 0.31342261018864015,
 'Heartbeat': 0.2838257824439533,
 'On the Street Where You Live': 0.30102661111446016,
 'One Door Away from Heaven': 0.36684993397872917,
 'Breathing Lessons': 0.29524124017828945,
 'Paradise': 0.3121137252449118,
 'The Gift': 0.37273581339425,
 'The Regulators': 0.32104534728885903,
 'Seize the Night': 0.31023672052281653,
 'Remember Me': 0.44350397368806643,
 'Four Past Midnight': 0.606215589972359,
 'The Guardian': 0.4051862985088033,
 'The Woman Next Door': 0.2726603665501976,
 'Choke': 0.3158326382658172,
 'Nightmares &amp; Dreamscapes': 0.44058125517582636,
 'Accident': 0.47300024955469155,
 'Icy Sparks': 0.38138951611150806,
 'Ellen Foster': 0.16309858202778754,
 "Daddy's Little Girl": 0.34021768568712984,
 'Back Roads': 0.5033538076140636,
 'Hideaway': 0.27685456322625185,
 'Sole Survivor': 0.2391612624697007,
 'Coming Home': 0.3369387673902318,
 'Bridge to Terabithia': 0.40982820570755557,
 'The Street Lawyer': 0.5443971653260115,
 'Presumed Innocent': 0.3049492887703665,
 'The Hours : A Novel': 0.3231061307585278,
 'The Body Farm': 0.35919600216954417,
 'WLD ACCORDNG GARP': 0.57957047741081,
 'Midnight': 0.3962776091650327,
 'Tara Road': 0.4436721934597911,
 'Pride and Prejudice': 0.5865421308541112,
 'Fatal Cure': 0.14511991888065376,
 "Charlotte's Web (Trophy Newbery)": 0.7355033230058675,
 'Absolute Power': 0.3084217400567661,
 'Black Notice': 0.3409051881395704,
 'Anne of Green Gables (Anne of Green Gables Novels (Paperback))': 0.6934290531398861,
 'Silence of the Lambs': 0.7811741405052944,
 'The House of the Spirits': 0.3587353230155928,
 'The Rainmaker': 0.3533789847772509,
 "The Lost Boy: A Foster Child's Search for the Love of a Family": 0.4595602023836175,
 'The Lottery Winner : Alvirah And Willy Stories': 0.2814606035616079,
 'A Prayer for Owen Meany': 0.394832818740163,
 '\\O\\" Is for Outlaw"': 0.40790215252011575,
 'Homecoming': 0.4552459961190651,
 'Mind Prey': 0.34986315982659866,
 'The Summons': 0.07398091198867571,
 'Chosen Prey': 0.38110665321905873,
 'Night Prey': 0.21652046765399172,
 'Rebecca': 0.7177455620725336,
 'High Fidelity': 0.3758454204309606,
 'Like Water for Chocolate: A Novel in Monthly Installments With Recipes, Romances and Home Remedies': 0.46995791866258274,
 'Tell No One': 0.38404891413995196,
 'A Child Called \\It\\": One Child\'s Courage to Survive"': 0.4420819861959511,
 'Men Are from Mars, Women Are from Venus: A Practical Guide for Improving Communication and Getting What You Want in Your Relationships': 0.29296255408142324,
 'The Green Mile': 0.2576271094266745,
 "Harry Potter and the Sorcerer's Stone (Book 1)": 0.8692119737776648,
 'F Is for Fugitive (Kinsey Millhone Mysteries (Paperback))': 0.6858266609977393,
 "From Potter's Field": 0.41273803836896894,
 'H Is for Homicide (Kinsey Millhone Mysteries (Paperback))': 0.47029817327869944,
 'A Wrinkle in Time': 0.7041983799260931,
 'Evening Class': 0.28004513140321957,
 'The Loop': 0.38169639625841156,
 'Dragonfly in Amber': 0.5581132758144092,
 'Smart Women': 0.34933734042499404,
 'Cold Sassy Tree': 0.4344372921181857,
 'Fall On Your Knees (Oprah #45)': 0.398073602683795,
 'Anne of the Island': 0.46714275750858797,

## **get KNN scores for a user**

In [31]:
# get user id and how many suggesions we want
# then we find what are the books user aleready liked
# for each book user liked, we find n_neighbors no of similar books / (distance, indices) paires
# and also we will calculate scores, for first book we will add all similraty scores to scores dic
# but in next iteration of liked_books list we willupdate exsing ones or add new if not exist fromeralier  loops
# finaly we may have sevaral times updated dic of  books for a particular user
def knn_scores_for_user(user_id, train_ratings_knn, pivot, n_neighbors=20):

    # books user rated highly (liked books)
    liked_books = train_ratings_knn[
        (train_ratings_knn["user_id"] == user_id) & (train_ratings_knn["ratings"] >=8)
        ]["title"].values

    scores = {}

    for book in liked_books:
        
        # skip if book not in pivot
        if book not in pivot.index: # pivot.index is title
            continue

        # get similar books
        # asks the trained KNN model: "Find books that are most similar to this book" (like wise go thorugh all book in liked_books)
        # pivot.loc[book] > selecting one row by book name, eg: Harry Potter then  [5, 0, 4, ...] > rating fingerprint of the book
        # KNN expects 2D input (matrix form) so reshape it > [[5, 0, 4, 5]]
        # trained model looks at all books it learned during .fit() and asks : Which books have rating patterns most similar to this vector?
        # Since used cosine similarity, KNN compares angles between vectors
        # returns >>> distances = [[0.00, 0.21, 0.33, 0.41, 0.55, ...]], indices = [[10, 25, 3, 17, 8, ...]] 20 suggestions for 'book'
        distance, indices = knn_model.kneighbors(
            pivot.loc[book].values.reshape(1, -1),
            n_neighbors=n_neighbors
        )

        # convert distance > similarity
        # Distance meaning: 0 = identical, 1 = totally different
        # But recommendation logic wants:1 = identical, 0 = no similarity
        # So flip it by 1 - ....
        similarities = 1 - distance.flatten() # flatten to 1D [0.00, 0.21, 0.33, 0.41, 0.55]

        # Converts positions >  book names
        # pivot.index[25] → "LOTR"
        # so let put 1D indices array into oit and get titles 1D array
        neighbors = pivot.index[indices.flatten()]

        # finally
        # neighbors    > book names
        # similarities > similarity score for each book

        # using above let create score dic
        # neighbors    = ["HP", "LOTR", "Twilight", "Narnia"]
        # similarities = [1.00, 0.79, 0.67, 0.59]
        # zip(neighbors, similarities) pairs them as ("HP", 1.00), loop runs once per neighbor
        for neighbor, similarity in zip(neighbors, similarities): # n_neighbors time this will loops

            # skip current book
            if neighbor == book:
                continue
                
            # If book already has score → get it, otherwise start from 0 > 0 + 0.67
            # then why (neighbor, 0) bcs, in next iteration > Suppose another liked book also suggests this book, scores["book1"] = 0.67 + 0.52 = 1.19
            scores[neighbor] = scores.get(neighbor, 0) + similarity
            
    # normalize 0–1
    if scores:
        max_score = max(scores.values())

        # Here, book is the key in each key-value pair, normaly loop using key
        for book in scores:
            scores[book] /= max_score

    # Which other books have rating patterns across users most similar to this liked book?
    # we have loop through all books user liked so finally we may have score dic that with several times updated same book to get strong or only one
    # then we may have more thn 20- books in score, bcs liked book list may add new ones
    return scores # title : distance from considered book(cumulative sum)

In [25]:
dic_knn_score = knn_scores_for_user(254, train_ratings_knn, book_pivot_knn, 20) # based on book
dic_knn_score # all score values for books for user 254 / how much each book match with user 0 - not, 1 - best

{'Harry Potter and the Goblet of Fire (Book 4)': 1.0,
 'Harry Potter and the Chamber of Secrets (Book 2)': 0.9950549664448084,
 'Harry Potter and the Order of the Phoenix (Book 5)': 0.904902662356348,
 "Harry Potter and the Sorcerer's Stone (Harry Potter (Paperback))": 0.5711971345239413,
 'The Fellowship of the Ring (The Lord of the Rings, Part 1)': 0.46502403324394476,
 'A Time to Kill': 0.33714300274809084,
 'The Joy Luck Club': 0.294357340955548,
 'Artemis Fowl (Artemis Fowl, Book 1)': 0.10667833698199361,
 'Interview with the Vampire': 0.19514078261104056,
 'The Firm': 0.259452510454476,
 "The Bonesetter's Daughter": 0.40308925481594876,
 'The Alienist': 0.3556234250333667,
 'Hannibal': 0.08727236826552717,
 "Tuesdays with Morrie: An Old Man, a Young Man, and Life's Greatest Lesson": 0.08713181800251438,
 'Red Dragon': 0.1945652721203487,
 "Full House (Janet Evanovich's Full Series)": 0.0777558157033673,
 'The Testament': 0.1567882585020533,
 'Wicked: The Life and Times of the Wicked Witch of the West': 0.29929834460581234,
 'A Is for Alibi (Kinsey Millhone Mysteries (Paperback))': 0.0741432304451053,
 'Harry Potter and the Prisoner of Azkaban (Book 3)': 0.8701977400404903,
 'Summer Sisters': 0.37146910655120396,
 'B Is for Burglar (Kinsey Millhone Mysteries (Paperback))': 0.2197362215222337,
 'Divine Secrets of the Ya-Ya Sisterhood: A Novel': 0.23946729053962632,
 'Snow Falling on Cedars': 0.20958491703287085,
 'The Client': 0.09993596214093507,
 "Bridget Jones's Diary": 0.17641756884186535,
 'Skipping Christmas': 0.09531904077022105,
 'A Painted House': 0.24785728750973973,
 'The Five People You Meet in Heaven': 0.1664281760678214,
 'The Bean Trees': 0.1509765601454517,
 'House of Sand and Fog': 0.2391761441014111,
 'The Lovely Bones: A Novel': 0.25488514928391814,
 'Good in Bed': 0.13190284783642722,
 'Bel Canto: A Novel': 0.12537785978565533,
 'The Poisonwood Bible: A Novel': 0.12439316393817225,
 'The Da Vinci Code': 0.20240221953913895,
 "Suzanne's Diary for Nicholas": 0.12295815642330231,
 "Where the Heart Is (Oprah's Book Club (Paperback))": 0.11896108732698235,
 'A Map of the World': 0.23186377953125856,
 'Little Altars Everywhere: A Novel': 0.11315649224285063,
 'Fried Green Tomatoes at the Whistle Stop Cafe': 0.10424229615173981,
 'Two for the Dough': 0.20281466046347457,
 "She's Come Undone (Oprah's Book Club)": 0.182414332507088,
 'The Red Tent (Bestselling Backlist)': 0.09482655461707722,
 'Sphere': 0.1549181077907547,
 'Dreamcatcher': 0.1093941771712383,
 'The Hunt for Red October': 0.10935626436547286,
 'Lord of the Flies': 0.09609224666316887,
 'The Pelican Brief': 0.08499536733966842,
 'Into Thin Air : A Personal Account of the Mt. Everest Disaster': 0.08124506951541945,
 'Nickel and Dimed: On (Not) Getting By in America': 0.08088689700193367,
 "The Kitchen God's Wife": 0.18309615295070375,
 'We Were the Mulvaneys': 0.16141630410648086,
 'A Prayer for Owen Meany': 0.1590777635925152,
 'Pop Goes the Weasel': 0.1304181969465276,
 'The Summons': 0.23248410047855056,
 'The Reader': 0.1212138401969777,
 'The Witching Hour (Lives of the Mayfair Witches)': 0.11691935001248836,
 'STONES FROM THE RIVER': 0.11427702446594984,
 'Violets Are Blue': 0.11203035059449233,
 'The Gift': 0.11162719548822565,
 "The Handmaid's Tale": 0.10976258807603195,
 'Breathing Lessons': 0.10971005142586601,
 'The Nanny Diaries: A Novel': 0.10703109065161188,
 'Hard Eight : A Stephanie Plum Novel (A Stephanie Plum Novel)': 0.11473603752961165,
 'Flesh and Blood': 0.11122840918122544,
 'The Last Precinct': 0.10885649576684127,
 'Three To Get Deadly : A Stephanie Plum Novel (A Stephanie Plum Novel)': 0.10749910973892521,
 'High Five (A Stephanie Plum Novel)': 0.10505140724379192,
 '\\O\\" Is for Outlaw"': 0.09822903673261213}

## Note

- SVD: I think the user would give this exact rating to an unseen book
- KNN: This book is similar to books the user liked. If they liked the originals, they will probably like this too, it will return how far each book from considering book as distance

## **Hybrid recommendation function**

## Why only unseen books

- Recommendations are meant to help discover new items the user hasn’t interacted with
- A user already knows or rated these books → no point recommending again
- so we only recommend unseen books

In [29]:
"""
    Hybrid recommendation combining popularity, KNN, and SVD scores.

    Parameters:
    - user_id: ID of the user
    - train_ratings_svd: DataFrame of all user ratings
    - svd_scores: dict of SVD predicted scores for the user
    - knn_scores: dict of KNN similarity scores for the user
    - top_n: number of recommendations to return
    - weights: dictionary of weights for pop/knn/svd

    Returns:
    - List of tuples: [(book_title, hybrid_score), ...] sorted descending
    """

def hybrid_recommend(user_id, n_suggestions=5, weights={"pop":0.2, "knn":0.5, "svd":0.3}):
    
    # Get unseen books
    all_books = train_ratings_svd["title"].unique() # unique titles not duplicated includes
    rated_books = train_ratings_svd[train_ratings_svd["user_id"]==user_id]["title"] # only book titles for particular user (user rated books)
    unseen_books = [b for b in all_books if b not in rated_books.values] # remove user already rated books 

    knn_scores = knn_scores_for_user(user_id, train_ratings_knn, book_pivot_knn, 20) # Calculated based on Book
    svd_scores = svd_scores_for_user(user_id, train_ratings_svd) # Calculated based on user

    
    hybrid_scores = {}

    for book in unseen_books:
        # Creates a boolean mask where only rows with book_title equal to your book variable are True
        # Select the pop_score column only for the rows where the mask is True
        # .values = Converts the resulting pandas Series into a NumPy array
        pop = popularity_df.loc[popularity_df["title"] == book, "pop_score"].values # since returning series we have always use 0 to access elt
        pop = pop[0] if len(pop) > 0 else 0

        # Get KNN and SVD scores (fallback to 0 if not found)
        knn = knn_scores.get(book, 0)
        svd = svd_scores.get(book, 0)

        # Now we have 3 metrices which is calculated accrofing to the Users, Books, Most rated, Let combine all together to get new book recoomendatoins,
        # Keep in mind, these all three mtrics have values  for each book how much is it fit to 
        # Weighted sum, hybrid_scores[book] default refer to key in score dic
        hybrid_scores[book] = weights["pop"] * pop + weights["knn"] * knn + weights["svd"] * svd

    # Sorts the keys (book titles) by their score in descending order
    # .items() returns list of key-value pairs as tuples (key, value)
    # [("Harry Potter 1", 0.78), ("LOTR1", 0.40), ...]
    # key=lambda x: x[1] → sort by the second element of each tuple (the score), x is a tuple (book_title, score), x[1] = score, descending/
    top_n_books = sorted(hybrid_scores.items(), key=lambda x: x[1], reverse=True)[:n_suggestions]
    
    return top_n_books

## Testing variabels

In [23]:
# # train_ratings_svd["title"].unique()
# ''' all_books
# array(['Pet Sematary', 'Good Omens', 'White Oleander : A Novel',
#        'The Subtle Knife (His Dark Materials, Book 2)',
#        'The Secret Life of Bees', 'Chocolat', 'Rising Tides',
#        'American Gods', 'Circle of Friends',
#        "She's Come Undone (Oprah's Book Club)", 'Night Whispers',
# '''

# # train_ratings_svd[train_ratings_svd["user_id"]==254]["title"]
# '''rated_books
# 0                                          Pet Sematary
# 1                                            Good Omens
# 2                              White Oleander : A Novel
# 3         The Subtle Knife (His Dark Materials, Book 2)
# 4                               The Secret Life of Bees
# 5                                              Chocolat
# 6                                          Rising Tides
# .
# .
# .
# '''

# # a = train_ratings_svd["title"].unique()
# # r =  train_ratings_svd[train_ratings_svd["user_id"]==254]["title"]
# # [b for b in a if b not in r.values]

# '''unseen_books
# ['Midnight in the Garden of Good and Evil: A Savannah Story',
#  'The Bourne Ultimatum',
#  'The King of Torts',
#  'The Eight',
#  'Skipping Christmas',....
#  ]
#  '''

# pop = popularity_df.loc[popularity_df["title"] == 254, "pop_score"].values
# '''
# array([0.08137981])
# '''
# pop

# pop = pop[0] if len(pop) > 0 else 1000
# pop

## **Predictions**

In [24]:
user_id_example = test_ratings["user_id"].iloc[50]
n_suggestions =10

rec_books = hybrid_recommend(
    user_id=user_id_example,
    n_suggestions=n_suggestions
)

print(f"Top {n_suggestions} Hybrid Recommendations for user {user_id_example}:\n")

for i in rec_books:
    print(i)

Top 10 Hybrid Recommendations for user 4017:

('Empire Falls', 0.7556700721100944)
('House of Sand and Fog', 0.6424764380544807)
('A Map of the World', 0.6311329760847699)
("Bridget Jones's Diary", 0.6109229190225414)
('The Da Vinci Code', 0.6097029070028901)
('The Poisonwood Bible: A Novel', 0.6009981510966321)
('SHIPPING NEWS', 0.5612083491139638)
('Wicked: The Life and Times of the Wicked Witch of the West', 0.533728212267795)
("The Pilot's Wife : A Novel", 0.5334453108086668)
('Fried Green Tomatoes at the Whistle Stop Cafe', 0.5294668206157682)

## **Evaluate hybrid model**

In [16]:
def precision_at_n_single_user(user_id, test_ratings_user, N=5, rate_threshold=8, top_n=10):
    '''
    recommended_books: list of book titles we got as recommendation as top_n_books_by_hybrid
    test_ratings_user: DataFrame of user's test ratings
    rate_threshold: rating to consider as user liked
    '''
    
    liked_books = test_ratings_user[
        (test_ratings_user["user_id"]==user_id) & (test_ratings_user["ratings"] >= rate_threshold)
        ]["title"].tolist()
    '''
    array(['The Dark Half', "Harry Potter and the Sorcerer's Stone (Book 1)"],
      dtype=object)
    '''
    # print(liked_books, "\n\n")
    if len(liked_books) == 0:
        return 0  # cannot evaluate

    # Getting recommendations
    recs = hybrid_recommend(
        user_id=user_id,
        train_ratings_svd= train_ratings_svd,
        train_ratings_knn=train_ratings_knn,
        book_pivot_knn=book_pivot_knn,
        top_n=10
    )

    if top_n < N:
        print("Values exceeded top_n < N")
        N = top_n
    
    # recommended_books[:N] >>> slices your recommended_books list to only take the top N recommendations
    # iterates over each book in the top N recommended books
    # if book in liked_books checks whether the current recommended book is in the list of books the user actually liked
    # If the condition is True, it adds 1 to the list. If False, it adds nothing
    recs = recs[:N] # when evaluating consider sevaral items bcs sometimews 10 is not good

    hits = []

    for book, score in recs:
        # print("book in recommended_books : ", book)
        if book in liked_books:
            hits.append(1)
            
    # print("hits : ", hits)
    precision = sum(hits) / N

    return precision

In [17]:
# Testing

liked_books = test_ratings[
        (test_ratings["user_id"] == 254) & (test_ratings["ratings"] >= 8)
        ]["title"].values

liked_books

array(['The Dark Half', "Harry Potter and the Sorcerer's Stone (Book 1)"],
      dtype=object)

In [18]:
precision = precision_at_n_single_user(
    user_id = user_id_example, 
    test_ratings_user = test_ratings, 
    N = 5,
    rate_threshold = 8,
    top_n = 10
)
print(f"precisison for user_id {user_id_example} : {precision*100} %")

precisison for user_id 4017 : 20.0 %

In [19]:
import numpy as np

precisions = []
count=0

for user_id, user_group  in test_ratings.groupby("user_id"):
    
    count += 1
    
    precision = precision_at_n_single_user(
        user_id = user_id, 
        test_ratings_user = user_group, # ONLY this user's test data
        N=5,
        rate_threshold=8, 
        top_n=10
    )

    # skip users with no liked books
    if precision is not None:
        precisions.append(precision)
    
    precisions.append(precision)
    
    if count % 100 == 0:
        print(count, " users cheked, so far precisison mean : ", np.mean(precisions))
        
print("\nFinal Precision@5:", np.mean(precisions))

100  users cheked, so far precisison mean :  0.07
200  users cheked, so far precisison mean :  0.07200000000000001
300  users cheked, so far precisison mean :  0.06866666666666667
400  users cheked, so far precisison mean :  0.0635
500  users cheked, so far precisison mean :  0.0608
600  users cheked, so far precisison mean :  0.05533333333333334
700  users cheked, so far precisison mean :  0.05542857142857143
800  users cheked, so far precisison mean :  0.0565

Final Precision@5: 0.055503512880562066

## Model Comparison — Precision@N

#### Popularity  = 0.011441307578008916
#### KNN         = 0.016956521739130436
#### SVD         = 0.021690590111642746
#### Hubrid      = 0.055503512880562066